esma
adnan-inci/tryCloudAutomation2 pull request #2
Opened 2021-02-07 16:18 UTC by esma17

finished my first test case US004_TC002

2021-02-08 02:32 UTC, mehmetdurkan requested changes

2021-02-08 02:32 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        List<WebElement> searchOutputs = Driver.getDriver().findElements(By.xpath("//a[contains(@aria-label,'Conversation,')]"));
Is there a certain reason to prefer list of elements here?

2021-02-08 02:32 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        WebElement searchBox = Driver.getDriver().findElement(By.xpath("//input[contains(@placeholder,'Search conversations')]"));
Try reusing driver object and throughout the class

2021-02-08 02:32 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        BrowserUtils.sleep(3);
Can you use dynamic and wait?

2021-02-08 02:32 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        WebElement actualResult= allMessages.get(allMessages.size() - 1);
I think you should add a comment here to mention about last message logic and why you needed

2021-02-08 04:27 UTC, esma17 commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        BrowserUtils.sleep(3);
The only reason I use sleep method is to observe by myself the process while automating it...

2021-02-08 04:53 UTC, esma17 commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        List<WebElement> searchOutputs = Driver.getDriver().findElements(By.xpath("//a[contains(@aria-label,'Conversation,')]"));
I was storing all users that displayed in search output box and selecting the first one . But, I changed it because it was not showing at index 0 the user I search all the time... thats why I used String format method now

2021-02-08 14:35 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        BrowserUtils.sleep(3);
When we check in, we need to delete temp statements beforehand. release branch should be clean.

2021-02-08 14:37 UTC, mehmetdurkan requested changes

2021-02-08 14:37 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +        WebElement user = driver.findElement(By.xpath(String.format(searchResult, searchInput)));
Very good

2021-02-08 14:37 UTC, mehmetdurkan commented on src/test/java/com/trycloud/tests/US004_TC002_esma.java
> +    public void teardown() {
Should we transfer this to TestBase

2021-02-09 03:19 UTC, jaja505 approved these changes

2021-02-09 03:19 UTC, merged